### ISSUE TITLE
Include info in README how to compile it

### ISSUE THREAD

**Issue by kenorb** [RJVB/afsctool#11]
```
$ make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by gingerbeardman** [comment]
See closed issues for how to compile

https://github.com/RJVB/afsctool/issues?q=is%3Aissue+is%3Aclosed

**Comment by gingerbeardman** [comment]
@kenorb if you make notes as you are compiling, you could edit the README and submit a Pull Request?

**Comment by gingerbeardman** [comment]
Done in https://github.com/RJVB/afsctool/pull/14

**Comment by gingerbeardman** [comment]
Please check the new readme and close if you think this issue is solved
