### ISSUE TITLE
lzvn compression failed on chunk #8

### ISSUE THREAD

**Issue by gingerbeardman** [RJVB/afsctool#31]
```
/Applications/PlayOnMac.app/Contents/Resources/unix/tools/bin/strings: lzvn compression failed on chunk #8
```

App: 
http://repository.playonmac.com/PlayOnMac/PlayOnMac_4.3.4.dmg

**Comment by RJVB** [comment]
Have you tried if the lzvn command line utility compresses the file?

**Comment by gingerbeardman** [comment]
I have not I'll do so asap

**Comment by RJVB** [comment]
Tried it myself (compresses fine), and found the explanation of your error.

This file is 9 "compression chunks" long, the last of which is 4 bytes. We already know that the LZVN compressor fails on data buffers shorter than 8 bytes.

The question now becomes how to handle this situation. Apple must have a solution if their compressor has the same limitation...

**Comment by gingerbeardman** [comment]
Interesting! Thanks Rene. These days I juggle a baby and keyboard/mouse.

**Comment by RJVB** [comment]
Right... good luck with that :)
The keyboard/mouse is for finding stuff to keep the morale high, like
https://www.google.com/search?q=baby+blender+jokes

? ;)

(Full disclosure: I only know about those because of that one American colleague from long ago ^^)
