### ISSUE TITLE
Is this afsctool the clear successor to the original? Should the homebrew afsctool formula point here instead?

### ISSUE THREAD

**Issue by varenc** [RJVB/afsctool#41]
The original v1.6.4 afsctool from brkirch seems abandoned but it's still the version that Homebrew's afsctool formula installs.  See here: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/afsctool.rb. The formula even applies [2 patches](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/afsctool.rb#L47) to the old code so that it will compile on recent macOS.  

Is this fork the clear de-facto successor? Would every, or nearly every, Homebrew user of afsctool v1.6.4 just be happier with this fork instead? I suspect so, but am honestly not sure!  All I'm really asking is does @RJVB think this is a good idea?

If this sounds good, then I'm volunteering myself to embark on a quest to try and get the Homebrew formula updated.

**Comment by RJVB** [comment]
I'm not going to emit any advice - other than

1) check my commit log to see what I did to the original code, esp. my earliest
2) MacPorts now provides my afsctool version (though probably under a different name, at brkirch's request; I'm not the port maintainer)

**Comment by gingerbeardman** [comment]
@varenc answer to your questions is "yes", but there has been some drama at homebrew and they say their policy is to not accept this fork as the latest version.

Search https://github.com/Homebrew/homebrew-core closed issues and PRs for afsctool

**Comment by duffyjp** [comment]
Here's a link to the Macports entry, if anyone is looking: [afscompress](https://ports.macports.org/port/afscompress/summary).

**Comment by RJVB** [comment]
I'm closing this because here's not the right place to discuss HB policies.
