### ISSUE TITLE
Is this identical to 'brew install afsctool' or is that the original version?

### ISSUE THREAD

**Issue by hstriepe** [RJVB/afsctool#46]
Subject says it all.

**Comment by gingerbeardman** [comment]
https://github.com/RJVB/afsctool/blob/master/README.md

**Comment by hstriepe** [comment]
Ok. I was trying to build on Monterey M1 12.0.1 with Xcode 13.1. Cmake was happy with prerequisites.
But I ended up with build errors - see attached.
Unlike your instruction I had to run cmake from the asfctool folder. Running from ./build created an error.
[Build log.txt](https://github.com/RJVB/afsctool/files/7590397/Build.log.txt)

**Comment by varenc** [comment]
I made #41 about this awhile back, but it sounds like the situation is more hopeful now.  The sentiment on https://github.com/Homebrew/homebrew-core/pull/88855 is looking positive.

**Comment by Botts85** [comment]
It's since been closed and not merged into the Master.  The commit isn't in any valid branch right now.

**Comment by RJVB** [comment]
Well, that s***s but it's not an afsctool issue as far as I'm concerned...
