### ISSUE TITLE
Are we ready for a new release?

### ISSUE THREAD

**Issue by nalzok** [RJVB/afsctool#49]
Currently the latest release is still from 2019, but the repository have received a lot of fixes and improvements since then. Do you think the master branch is stable enough to warrant a new release so that people using package managers like MacPorts can get the updated version?

**Comment by RJVB** [comment]
The code is stable in both branches AFAIAC and I know I should merge the lzfse branch into the master branch. Releases? I'm notoriously bad at decided what the version number should be (if not simply the date) ...

**Comment by nalzok** [comment]
Regarding the version number, what about `0.7.1` as suggested by [SemVer](https://semver.org/)? From my understanding, the patches mostly consist of backward compatible fixes, so it makes sense to increase the PATCH version.

> (if not simply the date)

Actually, there is another practice called [CalVer](https://calver.org/). Either is fine as long as the version numbers are consistent :)

**Comment by ylluminate** [comment]
Any news on a release front? The last PR merge was pretty important so I'm thinking a release is past due here... :º)
