### ISSUE TITLE
issues compiling

### ISSUE THREAD

**Issue by gingerbeardman** [RJVB/afsctool#5]
Last time I tried to compile was in https://github.com/RJVB/afsctool/issues/2#issuecomment-331187349 

I've got further this time, overcoming a few obstacles.

but once again hit a wall.

any help appreciated.

```bash
matt$ make
[ 12%] Building C object CMakeFiles/afsctool.dir/afsctool.c.o
[ 25%] Building CXX object CMakeFiles/afsctool.dir/main.cpp.o
[ 37%] Building CXX object CMakeFiles/afsctool.dir/ParallelProcess.cpp.o
[ 50%] Building CXX object CMakeFiles/afsctool.dir/Thread/Thread.cpp.o
/Users/matt/Downloads/2017-11-25/afsctool-master/Thread/Thread.cpp:16:26: warning: implicit conversion of
      NULL constant to 'DWORD' (aka 'unsigned long') [-Wnull-conversion]
DWORD thread2ThreadKey = NULL, thread2ThreadKeyClients = 0;
      ~~~~~~~~~~~~~~~~   ^~~~
                         0
/Users/matt/Downloads/2017-11-25/afsctool-master/Thread/Thread.cpp:143:22: warning: implicit conversion of
      NULL constant to 'DWORD' (aka 'unsigned long') [-Wnull-conversion]
                thread2ThreadKey = NULL;
                                 ~ ^~~~
                                   0
2 warnings generated.
[ 62%] Building CXX object CMakeFiles/afsctool.dir/CritSectEx/CritSectEx.cpp.o
[ 75%] Building CXX object CMakeFiles/afsctool.dir/CritSectEx/msemul.cpp.o
/Users/matt/Downloads/2017-11-25/afsctool-master/CritSectEx/msemul.cpp:37:10: fatal error: 
      'sparsehash/dense_hash_map' file not found
#include <sparsehash/dense_hash_map>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/afsctool.dir/CritSectEx/msemul.cpp.o] Error 1
make[1]: *** [CMakeFiles/afsctool.dir/all] Error 2
make: *** [all] Error 2
MacBookPro-Matt:afsctool-master matt$ fixopenwith
MacBookPro-Matt:afsctool-master matt$ make
[ 12%] Building CXX object CMakeFiles/afsctool.dir/CritSectEx/msemul.cpp.o
/Users/matt/Downloads/2017-11-25/afsctool-master/CritSectEx/msemul.cpp:37:10: fatal error: 
      'sparsehash/dense_hash_map' file not found
#include <sparsehash/dense_hash_map>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/afsctool.dir/CritSectEx/msemul.cpp.o] Error 1
make[1]: *** [CMakeFiles/afsctool.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by RJVB** [comment]
Do you maybe not have `sparsehash` installed?

I've made a few tweaks, if this is the case you'll now get an error from CMake. Just install the dependency wherever you have the other dependencies installed (it will be found via pkg-config).

**Comment by gingerbeardman** [comment]
thanks! I installed google-sparsehash using brew.

**Comment by gingerbeardman** [comment]
ps: i used source i downloaded yesterday, as today's source required sparsehash 2.0.3 and that is not yet in homebrew.

what do you use this afstool for? how do you have it configured?

**Comment by RJVB** [comment]
On Sunday November 26 2017 18:25:17 Matt Sephton wrote:
> ps: i used source i downloaded yesterday, as today's source required sparsehash 2.0.3 and that is not yet in homebrew.


Then HB is pretty out of date with their packaging, 2.0.3 isn't exactly new.

Also, I don't think I set a required version. CMake often behaves as if the latest version is required, in that case.

> what do you use this afstool for? how do you have it configured?

No need to configure anything, you call it from the commandline with the options you want to apply transparent compression to directories containing files that compress well, like text documents and executables, object files, libraries.

No point in running it on your collection of music or video files, or anything that is already compressed. Or on directories that contain files which will change all the time.

Also be careful not to run it on files that are open in some application unless you know exactly what you're doing.

**Comment by gingerbeardman** [comment]
Thanks, I edited my previous comment.

I meant what do you personally use the tool for? why did you feel the need to update it? what files do you need to compress regularly? sorry if it's none of my business :)

**Comment by RJVB** [comment]
I use it extensively on my source and build directories since those compress really well and can take up a lot of place. Idem for the ccache directory.

The README and commit history should give you some idea why I forked the project and have been keeping it updated. One important addition I made in the beginning was support for parallel processing, to speed up the operation.

**Comment by gingerbeardman** [comment]
Yes, thank you for adding parallel processing. 

I use the tool for similar reasons but had been using an old version I was updating myself to work on Sierra and High Sierra. 

In the README where you mention the performance difference not being enormously different. It took me a moment to realise that sentence referred to the difference between -j and -J and not the difference between regular and parallel processing version. 

Merci

**Comment by gingerbeardman** [comment]
I've moved to a new mac and need to build this again, but i'm getting a libz.dylib error with Cmake. Can you point me in the right direction? Merci!

```
MacBookPro-Matt:afsctool-1.6.8.6 matt$ cmake .
CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB: Found unsuitable version "1.2.3", but required is at
  least "1.2.8" (found /usr/lib/libz.dylib)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindZLIB.cmake:112 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!

```
