### ISSUE TITLE
Time Machine risks?

### ISSUE THREAD

**Issue by ylluminate** [RJVB/afsctool#55]
Does this work with Time Machine volumes or would it cause comparative errors for the backup process?

**Comment by RJVB** [comment]
TM volumes use specific, non-standard permissions. You can access the contents with standard Unix utilities (afsctool is that, in the end) but for instance you cannot restore them directly from there using `cp` and family. TM volumes also use directory hardlinks which don't exist elsewhere.

In short, I wouldn't try if I were you. 

However, compression is preserved, so your backups will be compressed if you data is.

There's one backdoor: TM volumes that live on a networked disk use a sparse disk image. The disk image file (or in this case, a collection of files in a bundle dir) can be compressed as far as I know. However, I've never tried afsctool on an AFP volume so I can neither confirm nor infirm if HFS compression is supported on those.

**Comment by ylluminate** [comment]
Interesting info there, thanks. I was aware of some of that, but like you, have been wary of trying it for unintended side effects. Are there any gotchas or dangers on any folders within the macOS system drive? I've contemplated running the tool on my entire home directory in Monterey, but again, I've been wary. Sure wish an app like Clusters from LateNiteSoft was still around, but for APFS insomuch that that felt like it really reduced concern/worry in various aspects.

**Comment by RJVB** [comment]
On Friday April 15 2022 09:43:58 ylluminate wrote:
> I've contemplated running the tool on my entire home directory in Monterey, but again, I've been wary.

The safest way to do this would be to run the tool as another (admin) user when you're not logged on. That's the best way to ensure that no files are open.
