### ISSUE TITLE
cmake libz.dylib error 

### ISSUE THREAD

**Issue by gingerbeardman** [RJVB/afsctool#7]
I've moved to a new mac and need to build this again, but i'm getting a libz.dylib error with Cmake. Can you point me in the right direction? Merci!

i'm using:

Mac OS X
10.13.2 (17C205)

Xcode
9.2 (9C40b)

cmake
3.10.2

what versions of software are you running to have an updated libz.dylib?

```
MacBookPro-Matt:afsctool-1.6.8.6 matt$ cmake .
CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB: Found unsuitable version "1.2.3", but required is at
  least "1.2.8" (found /usr/lib/libz.dylib)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindZLIB.cmake:112 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by gingerbeardman** [comment]
as a workaround i changed my local `CMakeLists.txt` to `find_package(ZLIB 1.2.3 REQUIRED)` and cmake and make gave me a binary

**Comment by RJVB** [comment]
I get all dependencies from MacPorts. Apparently you have HomeBrew installed, doesn't that provide a newer zlib? 1.2.3 is really old nowadays, and you may find that more recent versions even have better performance.

**Comment by gingerbeardman** [comment]
Brew does provide a newer zlib, but cmake doesn't find it? I've not used cmake much, sorry

**Comment by RJVB** [comment]
On Monday January 22 2018 17:16:00 Matt Sephton wrote:
>Brew does provide a newer zlib, but cmake doesn't find it? I've not used cmake much, sorry

Do you use cmake from HB? Normally it should search in the same tree where it is installed because cmake has a module to find a zlib installation.

Where are the HB zlib files installed? If the files zlib.h and libz.dylib have a common root like

/usr/local/include/zlib.h
/usr/local/lib/libz.dylib

you can invoke cmake with `-DZLIB_ROOT=/usr/local` .

**Comment by gingerbeardman** [comment]
brew says

> MacBookPro-Matt:~ matt$ brew info zlib
> zlib: stable 1.2.11 (bottled) [keg-only]
> General-purpose lossless data-compression library
> https://zlib.net/
> /usr/local/Cellar/zlib/1.2.11 (12 files, 373.4KB)
>   Poured from bottle on 2018-01-22 at 14:44:41
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/zlib.rb
> ==> Caveats
> This formula is keg-only, which means it was not symlinked into /usr/local,
> because macOS already provides this software and installing another version in
> parallel can cause all kinds of trouble.
> 
> For compilers to find this software you may need to set:
>     LDFLAGS:  -L/usr/local/opt/zlib/lib
>     CPPFLAGS: -I/usr/local/opt/zlib/include
> For pkg-config to find this software you may need to set:
>     PKG_CONFIG_PATH: /usr/local/opt/zlib/lib/pkgconfig

I've tried:

`cmake -DZLIB_ROOT=/usr/local/opt/zlib/ .`

`cmake -DZLIB_ROOT=/usr/local/Cellar/zlib/1.2.11/ .`

but no joy :(

**Comment by gingerbeardman** [comment]
OK, I got it!

`cmake -DZLIB_INCLUDE_DIR=/usr/local/Cellar/zlib/1.2.11/ .`

**Comment by RJVB** [comment]
Glad to know you figured it out.

HB shouldn't be making this so complicated...

**Comment by gingerbeardman** [comment]
I agree!

**Comment by biziclop** [comment]
Hi, this is how it worked for me.
I think adding `export` to `PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig` was the solution.

```
brew install google-sparsehash zlib cmake pkgconfig
cd ~/some/random/dir/afsc
git clone git://github.com/RJVB/afsctool
mkdir afsctool/build
cd afsctool/build
export PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig
cmake -Wno-dev ..
make
./afsctool
```
