### ISSUE TITLE
how many worker threads?

### ISSUE THREAD

**Issue by gingerbeardman** [RJVB/afsctool#8]
> Interestingly, the optimum performance (on large collections) is not necessarily
> obtained with as many worker threads as there are CPU cores. Collections with
> a significant number of very large files and many more smaller files can apparently
> be processed faster when using a rather larger number of workers, with a gain
> approaching the number of cores.

how large is "rather large"?

I am trying 200 as using thousands didn't really speed up the process due to the long initialisation.

**Comment by RJVB** [comment]
> how large is "rather large"?
> 
> I am trying 200 as using thousands didn't really speed up the process due to the long initialisation.

I cannot really answer that, as it will most likely depend on your collection of files, probably also on your CPU and possibly even on the zlib version. Make and model of the disk(s) you're using will also influence the optimal compromise.

Multithreading always comes with an overhead, and even with the -J option afsctool will not allow concurrent disk writes.
I wouldn't exceed 2-3 times the number of cores but as they say, YMMV. I personally just use -JNcores in general (Ncores being 4 in my case).

**Comment by gingerbeardman** [comment]
Thanks. That's useful information!
