### ISSUE TITLE
safe/recommended way to cancel/pause/resume process?

### ISSUE THREAD

**Issue by gingerbeardman** [RJVB/afsctool#9]
Is there a safe way to cancel or pause the process?

The most common way to cancel a process running in terminal is by pressing `Control+C` to send the interrupt signal. Is this safe/OK? 

Also, would/should I pause the process with:
`kill -STOP pid`

I would continue with:
`kill -CONT pid`

Thanks!

**Comment by RJVB** [comment]
>The most common way to cancel a process running in terminal is by pressing `Control+C` to send the interrupt signal.
>
>Is this safe/OK? 

I've tried to make it safe to do this, yes.

>would I be able to pause the process with:
>`kill -STOP pid`
>and continue with:
>`kill -CONT pid`

This should be safe but inherently risky when you do it in the middle of a file write. The STOP might not even be processed immediately during a write, in fact.

However: this is at your own risk. I'd avoid doing it during a big job containing crucial files myself.

**Comment by gingerbeardman** [comment]
My thoughts are that the STOP is processed when convenient, after certain operations.

But I'll do some reading and testing to confirm.

**Comment by RJVB** [comment]
That's what I think too.

I know for a fact that ^C is processed after certain operations. You can't use it to interrupt that low-level write of a multi-Gb file for instance, you'll have to wait until the op is done or use stronger means :)

**Comment by gingerbeardman** [comment]
That's fine, I want to do things the safe way.
